#!/bin/bash

# 切换工作目录
cd /workspaces/llvmta/testcases/dirforgdb

# 执行程序
/workspaces/llvmta/build/bin/llvmta \
  -disable-tail-calls \
  -float-abi=hard \
  -mattr=-neon,+vfp2 \
  -O0 \
  --ta-muarch-type=inorder \
  --ta-strict=false \
  --ta-memory-type=separatecaches \
  --ta-loop-bounds-file='/workspaces/llvmta/testcases/test/LoopAnnotations_Arm|NotOptimized|HardFloat.csv' \
  --ta-loop-lowerbounds-file='/workspaces/llvmta/testcases/test/LLoopAnnotations_Arm|NotOptimized|HardFloat.csv' \
  --core-info='/workspaces/llvmta/testcases/test/CoreInfo.json' \
  --core-numbers=2 \
  --shared-cache-Persistence-Analysis=true \
  --time-anomaly=true \
  --ta-multicore-type=zhangw \
  --ta-l2cache-persistence=elementwise \
  --ta-dcache-persistence=elementwise \
  --ta-icache-persistence=elementwise \
  --ta-dcache-linesize=16 \
  --ta-dcache-assoc=2 \
  --ta-dcache-nsets=16 \
  --ta-icache-linesize=16 \
  --ta-icache-assoc=2 \
  --ta-icache-nsets=16 \
  --ta-l2cache-linesize=16 \
  --ta-l2cache-assoc=4 \
  --ta-l2cache-nsets=32 \
  --ta-mem-latency=100 \
  --ta-L2-latency=10 \
  --ta-num-callsite-tokens=-1 \
  --ta-num-callee-tokens=-1 \
  --ta-num-loop-tokens=0 \
  --ta-loop-peel=0 \
  -debug-only= \
  optimized.ll
